// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MarginTrading.RiskManagerClient.Models
{
    using MarginTrading.RiskManagerClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CorrCoeffOverrideModel
    {
        /// <summary>
        /// Initializes a new instance of the CorrCoeffOverrideModel class.
        /// </summary>
        public CorrCoeffOverrideModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CorrCoeffOverrideModel class.
        /// </summary>
        public CorrCoeffOverrideModel(string assetX = default(string), string assetY = default(string), double? value = default(double?))
        {
            AssetX = assetX;
            AssetY = assetY;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assetX")]
        public string AssetX { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assetY")]
        public string AssetY { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public double? Value { get; set; }

    }
}
