// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MarginTrading.RiskManagerClient.Models
{
    using MarginTrading.RiskManagerClient;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// API DTO for setting overriding correlation coefficient value
    /// </summary>
    public partial class CorrCoeffOverrideModel
    {
        /// <summary>
        /// Initializes a new instance of the CorrCoeffOverrideModel class.
        /// </summary>
        public CorrCoeffOverrideModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CorrCoeffOverrideModel class.
        /// </summary>
        /// <param name="value">Coefficient value</param>
        /// <param name="assetX">Correlation matrix X coordiante</param>
        /// <param name="assetY">Correlation matrix Y coordinate</param>
        public CorrCoeffOverrideModel(double value, string assetX = default(string), string assetY = default(string))
        {
            AssetX = assetX;
            AssetY = assetY;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets correlation matrix X coordiante
        /// </summary>
        [JsonProperty(PropertyName = "assetX")]
        public string AssetX { get; set; }

        /// <summary>
        /// Gets or sets correlation matrix Y coordinate
        /// </summary>
        [JsonProperty(PropertyName = "assetY")]
        public string AssetY { get; set; }

        /// <summary>
        /// Gets or sets coefficient value
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public double Value { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
