// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MarginTrading.RiskManagerClient.Models
{
    using MarginTrading.RiskManagerClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ISystemParameters
    {
        /// <summary>
        /// Initializes a new instance of the ISystemParameters class.
        /// </summary>
        public ISystemParameters()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ISystemParameters class.
        /// </summary>
        public ISystemParameters(int? minimalQuotesVectorLength = default(int?), int? quoteSamplesVectorSize = default(int?), int? quoteSamplingIntervalInMiliseconds = default(int?), int? recalculationIntervalInMiliseconds = default(int?), int? reportGeneratorIntervalInMiliseconds = default(int?), int? hedgingServiceIntervalInMiliseconds = default(int?), double? quantileCoefficient = default(double?), int? accountTransactionDepthInDaysForPnL = default(int?), string marketMaker = default(string))
        {
            MinimalQuotesVectorLength = minimalQuotesVectorLength;
            QuoteSamplesVectorSize = quoteSamplesVectorSize;
            QuoteSamplingIntervalInMiliseconds = quoteSamplingIntervalInMiliseconds;
            RecalculationIntervalInMiliseconds = recalculationIntervalInMiliseconds;
            ReportGeneratorIntervalInMiliseconds = reportGeneratorIntervalInMiliseconds;
            HedgingServiceIntervalInMiliseconds = hedgingServiceIntervalInMiliseconds;
            QuantileCoefficient = quantileCoefficient;
            AccountTransactionDepthInDaysForPnL = accountTransactionDepthInDaysForPnL;
            MarketMaker = marketMaker;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "minimalQuotesVectorLength")]
        public int? MinimalQuotesVectorLength { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quoteSamplesVectorSize")]
        public int? QuoteSamplesVectorSize { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quoteSamplingIntervalInMiliseconds")]
        public int? QuoteSamplingIntervalInMiliseconds { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "recalculationIntervalInMiliseconds")]
        public int? RecalculationIntervalInMiliseconds { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "reportGeneratorIntervalInMiliseconds")]
        public int? ReportGeneratorIntervalInMiliseconds { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hedgingServiceIntervalInMiliseconds")]
        public int? HedgingServiceIntervalInMiliseconds { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quantileCoefficient")]
        public double? QuantileCoefficient { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountTransactionDepthInDaysForPnL")]
        public int? AccountTransactionDepthInDaysForPnL { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "marketMaker")]
        public string MarketMaker { get; set; }

    }
}
