// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MarginTrading.RiskManagerClient.Models
{
    using MarginTrading.RiskManagerClient;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for OrderCloseReason.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OrderCloseReason
    {
        [EnumMember(Value = "None")]
        None,
        [EnumMember(Value = "Close")]
        Close,
        [EnumMember(Value = "StopLoss")]
        StopLoss,
        [EnumMember(Value = "TakeProfit")]
        TakeProfit,
        [EnumMember(Value = "StopOut")]
        StopOut,
        [EnumMember(Value = "Canceled")]
        Canceled,
        [EnumMember(Value = "CanceledBySystem")]
        CanceledBySystem
    }
    internal static class OrderCloseReasonEnumExtension
    {
        internal static string ToSerializedValue(this OrderCloseReason? value)  =>
            value == null ? null : ((OrderCloseReason)value).ToSerializedValue();

        internal static string ToSerializedValue(this OrderCloseReason value)
        {
            switch( value )
            {
                case OrderCloseReason.None:
                    return "None";
                case OrderCloseReason.Close:
                    return "Close";
                case OrderCloseReason.StopLoss:
                    return "StopLoss";
                case OrderCloseReason.TakeProfit:
                    return "TakeProfit";
                case OrderCloseReason.StopOut:
                    return "StopOut";
                case OrderCloseReason.Canceled:
                    return "Canceled";
                case OrderCloseReason.CanceledBySystem:
                    return "CanceledBySystem";
            }
            return null;
        }

        internal static OrderCloseReason? ParseOrderCloseReason(this string value)
        {
            switch( value )
            {
                case "None":
                    return OrderCloseReason.None;
                case "Close":
                    return OrderCloseReason.Close;
                case "StopLoss":
                    return OrderCloseReason.StopLoss;
                case "TakeProfit":
                    return OrderCloseReason.TakeProfit;
                case "StopOut":
                    return OrderCloseReason.StopOut;
                case "Canceled":
                    return OrderCloseReason.Canceled;
                case "CanceledBySystem":
                    return OrderCloseReason.CanceledBySystem;
            }
            return null;
        }
    }
}
