// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MarginTrading.RiskManagerClient.Models
{
    using MarginTrading.RiskManagerClient;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for OrderFillType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OrderFillType
    {
        [EnumMember(Value = "FillOrKill")]
        FillOrKill,
        [EnumMember(Value = "PartialFill")]
        PartialFill
    }
    internal static class OrderFillTypeEnumExtension
    {
        internal static string ToSerializedValue(this OrderFillType? value)  =>
            value == null ? null : ((OrderFillType)value).ToSerializedValue();

        internal static string ToSerializedValue(this OrderFillType value)
        {
            switch( value )
            {
                case OrderFillType.FillOrKill:
                    return "FillOrKill";
                case OrderFillType.PartialFill:
                    return "PartialFill";
            }
            return null;
        }

        internal static OrderFillType? ParseOrderFillType(this string value)
        {
            switch( value )
            {
                case "FillOrKill":
                    return OrderFillType.FillOrKill;
                case "PartialFill":
                    return OrderFillType.PartialFill;
            }
            return null;
        }
    }
}
