// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MarginTrading.RiskManagerClient.Models
{
    using MarginTrading.RiskManagerClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PositionLimit
    {
        /// <summary>
        /// Initializes a new instance of the PositionLimit class.
        /// </summary>
        public PositionLimit()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PositionLimit class.
        /// </summary>
        public PositionLimit(string assetId = default(string), string counterPartyId = default(string), double? lowerSoftLimit = default(double?), double? lowerHardLimit = default(double?), double? upperSoftLimit = default(double?), double? upperHardLimit = default(double?))
        {
            AssetId = assetId;
            CounterPartyId = counterPartyId;
            LowerSoftLimit = lowerSoftLimit;
            LowerHardLimit = lowerHardLimit;
            UpperSoftLimit = upperSoftLimit;
            UpperHardLimit = upperHardLimit;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "counterPartyId")]
        public string CounterPartyId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lowerSoftLimit")]
        public double? LowerSoftLimit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lowerHardLimit")]
        public double? LowerHardLimit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "upperSoftLimit")]
        public double? UpperSoftLimit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "upperHardLimit")]
        public double? UpperHardLimit { get; set; }

    }
}
