// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MarginTrading.RiskManagerClient.Models
{
    using MarginTrading.RiskManagerClient;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for PositionStatus.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PositionStatus
    {
        [EnumMember(Value = "Open")]
        Open,
        [EnumMember(Value = "Closed")]
        Closed
    }
    internal static class PositionStatusEnumExtension
    {
        internal static string ToSerializedValue(this PositionStatus? value)  =>
            value == null ? null : ((PositionStatus)value).ToSerializedValue();

        internal static string ToSerializedValue(this PositionStatus value)
        {
            switch( value )
            {
                case PositionStatus.Open:
                    return "Open";
                case PositionStatus.Closed:
                    return "Closed";
            }
            return null;
        }

        internal static PositionStatus? ParsePositionStatus(this string value)
        {
            switch( value )
            {
                case "Open":
                    return PositionStatus.Open;
                case "Closed":
                    return PositionStatus.Closed;
            }
            return null;
        }
    }
}
