// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MarginTrading.RiskManagerClient.Models
{
    using MarginTrading.RiskManagerClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PVaRConcentrationLimit
    {
        /// <summary>
        /// Initializes a new instance of the PVaRConcentrationLimit class.
        /// </summary>
        public PVaRConcentrationLimit()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PVaRConcentrationLimit class.
        /// </summary>
        public PVaRConcentrationLimit(string traderCounterPartyId = default(string), string makerCounterPartyId = default(string), double? treshold = default(double?), double? softLimitPercentage = default(double?), double? hardLimitPercentage = default(double?))
        {
            TraderCounterPartyId = traderCounterPartyId;
            MakerCounterPartyId = makerCounterPartyId;
            Treshold = treshold;
            SoftLimitPercentage = softLimitPercentage;
            HardLimitPercentage = hardLimitPercentage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "traderCounterPartyId")]
        public string TraderCounterPartyId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "makerCounterPartyId")]
        public string MakerCounterPartyId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "treshold")]
        public double? Treshold { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "softLimitPercentage")]
        public double? SoftLimitPercentage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hardLimitPercentage")]
        public double? HardLimitPercentage { get; set; }

    }
}
