// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MarginTrading.RiskManagerClient.Models
{
    using MarginTrading.RiskManagerClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class StDevCoeff
    {
        /// <summary>
        /// Initializes a new instance of the StDevCoeff class.
        /// </summary>
        public StDevCoeff()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the StDevCoeff class.
        /// </summary>
        public StDevCoeff(string asset = default(string), double? calculatedValue = default(double?), bool? overridden = default(bool?), double? overriddenValue = default(double?))
        {
            Asset = asset;
            CalculatedValue = calculatedValue;
            Overridden = overridden;
            OverriddenValue = overriddenValue;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "asset")]
        public string Asset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "calculatedValue")]
        public double? CalculatedValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "overridden")]
        public bool? Overridden { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "overriddenValue")]
        public double? OverriddenValue { get; set; }

    }
}
