// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MarginTrading.RiskManagerClient.Models
{
    using MarginTrading.RiskManagerClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SystemParametersResponse
    {
        /// <summary>
        /// Initializes a new instance of the SystemParametersResponse class.
        /// </summary>
        public SystemParametersResponse()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SystemParametersResponse class.
        /// </summary>
        public SystemParametersResponse(int minimalQuotesVectorLength, int quoteSamplesVectorSize, int quoteSamplingIntervalInMiliseconds, int recalculationIntervalInMiliseconds, int batchReportIntervalInMiliseconds, int reportGeneratorIntervalInMiliseconds, int hedgingServiceIntervalInMiliseconds, int externalPositionIntervalInMiliseconds, int externalAccountIntervalInMiliseconds, double globalQuoteChangeSpeed, double quantileCoefficient, int accountTransactionDepthInDaysForPnL, string marketMaker = default(string))
        {
            MinimalQuotesVectorLength = minimalQuotesVectorLength;
            QuoteSamplesVectorSize = quoteSamplesVectorSize;
            QuoteSamplingIntervalInMiliseconds = quoteSamplingIntervalInMiliseconds;
            RecalculationIntervalInMiliseconds = recalculationIntervalInMiliseconds;
            BatchReportIntervalInMiliseconds = batchReportIntervalInMiliseconds;
            ReportGeneratorIntervalInMiliseconds = reportGeneratorIntervalInMiliseconds;
            HedgingServiceIntervalInMiliseconds = hedgingServiceIntervalInMiliseconds;
            ExternalPositionIntervalInMiliseconds = externalPositionIntervalInMiliseconds;
            ExternalAccountIntervalInMiliseconds = externalAccountIntervalInMiliseconds;
            GlobalQuoteChangeSpeed = globalQuoteChangeSpeed;
            QuantileCoefficient = quantileCoefficient;
            AccountTransactionDepthInDaysForPnL = accountTransactionDepthInDaysForPnL;
            MarketMaker = marketMaker;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "minimalQuotesVectorLength")]
        public int MinimalQuotesVectorLength { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quoteSamplesVectorSize")]
        public int QuoteSamplesVectorSize { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quoteSamplingIntervalInMiliseconds")]
        public int QuoteSamplingIntervalInMiliseconds { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "recalculationIntervalInMiliseconds")]
        public int RecalculationIntervalInMiliseconds { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "batchReportIntervalInMiliseconds")]
        public int BatchReportIntervalInMiliseconds { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "reportGeneratorIntervalInMiliseconds")]
        public int ReportGeneratorIntervalInMiliseconds { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hedgingServiceIntervalInMiliseconds")]
        public int HedgingServiceIntervalInMiliseconds { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "externalPositionIntervalInMiliseconds")]
        public int ExternalPositionIntervalInMiliseconds { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "externalAccountIntervalInMiliseconds")]
        public int ExternalAccountIntervalInMiliseconds { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "globalQuoteChangeSpeed")]
        public double GlobalQuoteChangeSpeed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quantileCoefficient")]
        public double QuantileCoefficient { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountTransactionDepthInDaysForPnL")]
        public int AccountTransactionDepthInDaysForPnL { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "marketMaker")]
        public string MarketMaker { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
