// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MarginTrading.RiskManagerClient.Models
{
    using MarginTrading.RiskManagerClient;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for TradingOrderDirection.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TradingOrderDirection
    {
        [EnumMember(Value = "Buy")]
        Buy,
        [EnumMember(Value = "Sell")]
        Sell
    }
    internal static class TradingOrderDirectionEnumExtension
    {
        internal static string ToSerializedValue(this TradingOrderDirection? value)  =>
            value == null ? null : ((TradingOrderDirection)value).ToSerializedValue();

        internal static string ToSerializedValue(this TradingOrderDirection value)
        {
            switch( value )
            {
                case TradingOrderDirection.Buy:
                    return "Buy";
                case TradingOrderDirection.Sell:
                    return "Sell";
            }
            return null;
        }

        internal static TradingOrderDirection? ParseTradingOrderDirection(this string value)
        {
            switch( value )
            {
                case "Buy":
                    return TradingOrderDirection.Buy;
                case "Sell":
                    return TradingOrderDirection.Sell;
            }
            return null;
        }
    }
}
